version: '3.8'

services:
  db:
    image: postgres:13
    container_name: task_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecurepassword
      POSTGRES_DB: task_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task_network

  redis:
    image: redis:alpine
    container_name: task_redis
    ports:
      - "6379:6379"
    networks:
      - task_network

volumes:
  postgres_data:

networks:
  task_network:
    driver: bridge